CREATE TABLE TAIKHOAN (
    MATK INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    HOTEN VARCHAR(100),
    MAVTTK INT,
    NGDKTK DATE,
    FOREIGN KEY (MAVTTK) REFERENCES VAITROTK(MAVT)
);
CREATE TABLE VAITROTK (
    MAVT INT PRIMARY KEY,-- nhatuyendung hoac ungvien
    TENVT VARCHAR(50) NOT NULL
);
CREATE TABLE UNGVIEN (
    MAUV INT PRIMARY KEY AUTO_INCREMENT,
    TENUV VARCHAR(100),
    GIOITINH ENUM('Nam', 'Nữ', 'Khác'),
    CHUYENMON VARCHAR(100),
    CVHT VARCHAR(255), 
    SONAMKN INT,
    NGAYSINH DATE,
    NGDKTK DATE
);
CREATE TABLE NHATUYENDUNG (
    MANTD INT PRIMARY KEY AUTO_INCREMENT,
    TENNTD VARCHAR(100),
    EMAIL VARCHAR(100),
    DIACHI VARCHAR(255)
);
CREATE TABLE BAIDANG (
    MABD INT PRIMARY KEY AUTO_INCREMENT,
    TENCV VARCHAR(100),
    TENNGANH VARCHAR(100),
    HTLV VARCHAR(50), -- hình thức làm việc
    LUONG VARCHAR(50),
    KINHNGHIEM VARCHAR(100),
    CAPBAC VARCHAR(50),
    DIACHI VARCHAR(255),
    PHUCLOI TEXT,
    MOTACV TEXT,
    YEUCAUCV TEXT,
    THOIGIANLV VARCHAR(100),
    TTKHAC TEXT,
    HINHANH VARCHAR(255),
    MANTD INT,
    FOREIGN KEY (MANTD) REFERENCES NHATUYENDUNG(MANTD)
);
CREATE TABLE CHITIET_UNGTUYEN (
    MACT INT PRIMARY KEY AUTO_INCREMENT,
    MAUV INT,
    MABD INT,
    NGAYUNGTUYEN DATE,
    FOREIGN KEY (MAUV) REFERENCES UNGVIEN(MAUV),
    FOREIGN KEY (MABD) REFERENCES BAIDANG(MABD)
);
CREATE TABLE PHONGVAN (
    MAPV INT PRIMARY KEY AUTO_INCREMENT,
    MACT INT NOT NULL,
    NGAYPV DATE,
    TRANGTHAI VARCHAR(50),
    FOREIGN KEY (MACT) REFERENCES CHITIET_UNGTUYEN(MACT)
);
CREATE TABLE BAITEST (
    MABAITEST INT PRIMARY KEY AUTO_INCREMENT,
    MANTD INT,
    TENBAITEST VARCHAR(100),
    FILEBT VARCHAR(255),
    LINKGGFORM VARCHAR(255),
    LINKBTKHAC VARCHAR(255),
    GHICHU TEXT,
    FOREIGN KEY (MANTD) REFERENCES NHATUYENDUNG(MANTD)
);

